export const ADMIN_ADD = "ADMIN_ADD";
export const ADMIN_UPDATE = "ADMIN_UPDATE";
export const ADMIN_DELETE = "ADMIN_DELETE";
export const ADMIN_SHOW = "ADMIN_SHOW";
export const ADMIN_SHOW_ALL = "ADMIN_SHOW_ALL";
export const ADMIN_REDIRECT_TO_UPDATE = "ADMIN_REDIRECT_TO_UPDATE";
export const ADMIN_DISPLAY_MESSAGE = "ADMIN_DISPLAY_MESSAGE";
