export const CATEGORY_ADD = "CATEGORY_ADD";
export const CATEGORY_UPDATE = "CATEGORY_UPDATE";
export const CATEGORY_SHOW = "CATEGORY_SHOW";
export const CATEGORY_SHOW_ALL = "CATEGORY_SHOW_ALL";
export const CATEGORY_DISPLAY_MESSAGE = "CATEGORY_DISPLAY_MESSAGE";
export const CATEGORY_REDIRECT_TO_UPDATE = "CATEGORY_REDIRECT_TO_UPDATE";
export const CATEGORY_REDIRECT_TO_SHOW = "CATEGORY_REDIRECT_TO_SHOW";