export const CUSTOMER_ADD = "CUSTOMER_ADD";
export const CUSTOMER_UPDATE = "CUSTOMER_UPDATE";
export const CUSTOMER_SHOW = "CUSTOMER_SHOW";
export const CUSTOMER_SHOW_ALL = "CUSTOMER_SHOW_ALL";
export const CUSTOMER_DISPLAY_MESSAGE = "CUSTOMER_DISPLAY_MESSAGE";
export const CUSTOMER_REDIRECT_TO_UPDATE = "CUSTOMER_REDIRECT_TO_UPDATE";
export const CUSTOMER_REDIRECT_TO_SHOW = "CUSTOMER_REDIRECT_TO_SHOW";

export const CUSTOMER_ADD_SWEET_ORDER_ID = "CUSTOMER_ADD_SWEET_ORDER_ID";
export const CUSTOMER_REMOVE_SWEET_ORDER_ID = "CUSTOMER_REMOVE_SWEET_ORDER_ID";
export const CUSTOMER_RESET_SWEET_ORDER_IDS = "CUSTOMER_RESET_SWEET_ORDER_IDS";

export const CUSTOMER_ADD_SWEET_ITEM_ID = "CUSTOMER_ADD_SWEET_ITEM_ID";
export const CUSTOMER_REMOVE_SWEET_ITEM_ID = "CUSTOMER_REMOVE_SWEET_ITEM_ID";
export const CUSTOMER_RESET_SWEET_ITEM_IDS = "CUSTOMER_RESET_SWEET_ITEM_IDS";

export const CUSTOMER_ADD_CART_ID = "CUSTOMER_ADD_CART_ID";
export const CUSTOMER_REMOVE_CART_ID = "CUSTOMER_REMOVE_CART_ID";
export const CUSTOMER_RESET_CART_IDS = "CUSTOMER_RESET_CART_IDS"