export var USER_LOGIN = "USER_LOGIN";
export var USER_LOGOUT = "USER_LOGOUT";
export var USER_LOGIN_SUCCESSFUL = "USER_LOGIN_SUCCESSFUL";
export var USER_LOGOUT_SUCCESSFUL = "USER_LOGOUT_SUCCESSFUL";
export var USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export var USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED";
export var LOGIN_SET_LOGIN_STATE = "LOGIN_SET_LOGIN_STATE";