
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const SHOW_ALL_PRODUCTS = "SHOW_ALL_PRODUCTS";
export const SHOW_SELECTED_PRODUCT = "SHOW_SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";
export const DISPLAY_MESSAGE = "DISPLAY_MESSAGE";
export const REDIRECT_TO_SHOW = "REDIRECT_TO_SHOW";
export const REDIRECT_TO_UPDATE = "REDIRECT_TO_UPDATE";
