export const ProductActionTypes={
ADD_PRODUCT : "ADD_PRODUCT",
UPDATE_PRODUCT : "UPDATE_PRODUCT",
SHOW_ALL_PRODUCTS : "SHOW_ALL_PRODUCTS",
SHOW_SELECTED_PRODUCT : "SHOW_SELECTED_PRODUCT",
REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT"
}