export const SWEET_ITEM_ADD = "SWEET_ITEM_ADD";
export const SWEET_ITEM_UPDATE = "SWEET_ITEM_UPDATE";
export const SWEET_ITEM_SHOW = "SWEET_ITEM_SHOW";
export const SWEET_ITEM_SHOW_ALL = "SWEET_ITEM_SHOW_ALL";
export const SWEET_ITEM_DISPLAY_MESSAGE = "SWEET_ITEM_DISPLAY_MESSAGE";
export const SWEET_ITEM_REDIRECT_TO_UPDATE = "SWEET_ITEM_REDIRECT_TO_UPDATE";
export const SWEET_ITEM_REDIRECT_TO_SHOW = "SWEET_ITEM_REDIRECT_TO_SHOW";
export const SWEET_ITEM_ADD_PRODUCT_ID = "SWEET_ITEM_ADD_PRODUCT_ID";
export const SWEET_ITEM_REMOVE_PRODUCT_ID = "SWEET_ITEM_REMOVE_PRODUCT_ID";
export const SWEET_ITEM_RESET_PRODUCT_IDS = "SWEET_ITEM_RESET_PRODUCT_IDS";
export const SWEET_ITEM_ADD_SWEET_ORDER_ID = "SWEET_ITEM_ADD_SWEET_ORDER_ID";
export const SWEET_ITEM_REMOVE_SWEET_ORDER_ID = "SWEET_ITEM_REMOVE_SWEET_ORDER_ID";
export const SWEET_ITEM_RESET_SWEET_ORDER_IDS = "SWEET_ITEM_RESET_SWEET_ORDER_IDS"
            