export const SWEET_ORDER_SHOW = "SWEET_ORDER_SHOW";
export const SWEET_ORDER_DISPLAY_MESSAGE = "SWEET_ORDER_DISPLAY_MESSAGE";
export const SWEET_ORDER_REDIRECT_TO_UPDATE = "SWEET_ORDER_REDIRECT_TO_UPDATE";